# Generated by Django 4.2.19 on 2025-02-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=300)),
                ('picture', models.ImageField(null=True, upload_to='series')),
                ('date', models.DateField()),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=150)),
                ('categories', models.ManyToManyField(to='anime_blog.category')),
            ],
        ),
    ]
