# Generated by Django 4.2.19 on 2025-02-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='description',
            field=models.TextField(max_length=700),
        ),
    ]
